# Extends https://github.com/mundialis/github-workflows/blob/main/linting-config-examples/ruff.toml

lint.ignore = [
    # See https://docs.astral.sh/ruff/rules/
    # TODO: fix lint issues or use lint_per-file-ignores
    "A001",
    "A002",
    "ANN001",
    "ANN201",
    "ANN202",
    "ANN204",
    "BLE001",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D205",
    "D400",
    "D401",
    "D404",
    "D415",
    "DTZ003",
    "E501",
    "E721",
    "F841",
    "N801",
    "N802",
    "N803",
    "N806",
    "N816",
    "N999",
    "PLR0911",
    "PLR0912",
    "PLR1702",
    "PLR6301",
    "PLW1514",
    "PLW2901",
    "PT012",
    "PTH100",
    "PTH103",
    "PTH112",
    "PTH118",
    "PTH120",
    "PTH123",
    "RET503",
    "RET504",
    "RUF012",
    "RUF067",
    "S105",
    "S108",
    "S113",
    "S201",
    "S318",
    "S408",
    "S701",
    "SIM108",
    "SLF001",
    "TRY002",
    "TRY003",
    "TRY300",
    "TRY301",
]

# [lint.per-file-ignores]
# Define file-specific linting rule ignores
# "lib_dop/r_dop_import_lib.py" = ["ERA001", "PLR2004"]
